name: Build bv-streamer

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ws-streamer-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: bv-streamer-*
        if: startsWith(github.ref, 'refs/tags/')
